# Generated by Django 4.2.4 on 2023-08-26 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 16, 49, 34, 2412)),
        ),
    ]
